front/routes/web.php
<?php

use App\Http\Controllers\RegistreIncidenceController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('home');

Route::resource('registre-incidence', RegistreIncidenceController::class)->only(['index', 'create', 'show', 'edit']);
Route::get('registre-incidence-low', [RegistreIncidenceController::class, 'indexLow'])->name('registre-incidence.index-low');

front/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'token',
        'token_type',
        'created_at',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

front/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

front/app/Http/Controllers/RegistreIncidenceController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;

class RegistreIncidenceController extends Controller
{
    public function __construct() {
        $this->middleware('has-auth-token', ['only' => ['create', 'edit', 'delete']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('reg-incid.index');
    }

    public function indexLow()
    {
        $response = Http::get('http://nginx:80/api/registre-incidence/index-low');
        return view('reg-incid.index-low', [
            'data' => $response->json()['collection']
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('reg-incid.create');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('reg-incid.show', [
            'indice' => $id
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('reg-incid.edit', [
            'indice' => $id
        ]);
    }
}

front/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

front/app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

front/resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="auth-token" content="{{ session('auth-token') }}" type="{{ session('auth-token-type') }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

    <!-- Styles -->
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
</head>

<body>
    <nav class="mt-6 mx-4">
        <a href="{{ route('home') }}" class="text-blue-800 border border-blue-300 p-1 rounded">Home</a>
        @if (session()->has('auth-token'))
            <a href="{{ route('auth.profile') }}" class="text-blue-800 border border-blue-300 p-1 rounded">Profil
                utilisateur</a>
            <a href="{{ route('auth.destroy') }}"
                class="text-blue-800 border border-blue-300 p-1 rounded">Déconnexion</a>
        @else
            <a href="{{ route('auth.register') }}"
                class="text-blue-800 border border-blue-300 p-1 rounded">S'inscrire</a>
            <a href="{{ route('auth.create') }}" class="text-blue-800 border border-blue-300 p-1 rounded">Se
                connecter</a>
        @endauth
        <a href="{{ route('registre-incidence.index') }}"
            class="text-blue-800 border border-blue-300 p-1 rounded">Registre incidence</a>
        <a href="{{ route('registre-incidence.index-low') }}"
            class="text-blue-800 border border-blue-300 p-1 rounded">Registre incidence (version lourde)</a>
</nav>

<main class="mx-8 mt-4">
    @yield('body')
</main>

<script src="{{ mix('js/app.js') }}"></script>
@yield('body-javascript')
</body>

</html>

front/resources/views/reg-incid/create.blade.php
@extends('layout')

@section('body')
    <main class="mt-16 mx-auto lg:w-1/3 md:1/2 w-full">
        <div class="w-full max-w-md">
            <form class="bg-white shadow-lg rounded px-12 pt-6 pb-8 mb-4" name="regIncidForm" onsubmit="submitForm()">
                <!-- @csrf -->
                <div class="text-gray-800 text-2xl flex justify-center border-b-2 py-2 mb-4">
                    Formulaire d'ajout dans le registre d'incidence
                </div>
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-normal mb-2" for="date">
                        Date
                    </label>
                    <input
                        class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                        name="date" v-model="form.date" type="date" required="" autofocus="">
                </div>
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-normal mb-2" for="nomRegion">
                        Nom de la région
                    </label>
                    <input
                        class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
                        v-model="form.nomRegion" type="nomRegion" name="nomRegion" required="">
                </div>
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-normal mb-2" for="numRegion">
                        Numéro de la région
                    </label>
                    <input
                        class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
                        v-model="form.numRegion" type="numRegion" name="numRegion" required="">
                </div>
                <div class="mb-6">
                    <label class="block text-gray-700 text-sm font-normal mb-2" for="countRea">
                        Nombre de réanimations
                    </label>
                    <input
                        class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
                        v-model="form.countRea" type="numRegion" name="countRea" required="">
                </div>
                <div class="flex items-center justify-between">
                    <button
                        class="px-4 py-2 rounded text-white inline-block shadow-lg bg-blue-500 hover:bg-blue-600 focus:bg-blue-700"
                        type="submit">Ajouter cet élément</button>
                </div>

                <p class="mt-2 text-green-500 text-center" id="success-text"></p>
                <p class="mt-2 text-red-500 text-center" id="error-text"></p>
            </form>
        </div>
    </main>
@endsection

@section('body-javascript')
    <script>
        function submitForm() {
            event.preventDefault();
            const authTokenTag = document.querySelector('meta[name="auth-token"]');
            const textError = document.querySelector('#error-text');
            const textSuccess = document.querySelector("#success-text");

            if (authTokenTag.getAttribute('type') !== 'bearer' || !authTokenTag.content) {
                axios.post("http://localhost:8080/api/registre-incidence", {
                    "jour": document.forms['regIncidForm'].elements['date'].value,
                    "nomReg": document.forms['regIncidForm'].elements['nomRegion'].value,
                    "numReg": document.forms['regIncidForm'].elements['numRegion'].value,
                    "incid_rea": document.forms['regIncidForm'].elements['countRea'].value
                }, {
                    headers: {
                        authorization: `Bearer ${authTokenTag.content}`
                    }
                }).then((response) => {
                    textSuccess.textContent =
                        "Element enregistré à l'identifiant " + response.data.idModel;

                }).catch((err) => {
                    if (err.response) {
                        switch (err.response.status) {
                            case 400:
                                // Erreur dans le formulaire
                                let errors = "";
                                for (const errorField in err.response.data.errors) {
                                    if (Object.hasOwnProperty.call(err.response.data.errors, errorField)) {
                                        const errorMessage = err.response.data.errors[errorField];
                                        errors += errorMessage + " ";
                                    }
                                }
                                textError.textContent =
                                    "Le formulaire envoyé a rencontré une/des erreur(s) : " + errors;

                                break;
                            case 401:
                                textError.textContent = "Utilisateur non connecté";

                                break;
                            case 403:
                                textError.textContent =
                                    "Vous n'avez pas les droits nécéssaire pour ajouter un élément";
                                break;
                            default:
                                textError.textContent = "Erreur inconnue";
                                break;
                        }
                    } else {
                        // Erreur inconnue
                        textError.textContent = "Erreur inconnue";
                    }
                });
            } else {
                document.querySelector("#error-text").textContent = "L'utilisateur n'est pas connecté";
            }
        }

    </script>
@endsection

front/resources/views/reg-incid/index-low.blade.php
@extends('layout')

@section('body')
    {{-- Utilisé pour afficher certains messages de succès --}}
    <div class="hidden mb-8 block text-sm text-left text-green-600 bg-green-200 border border-green-400 h-12 flex items-center p-4 rounded-sm"
        id="success-text" role="alert">
        Succès...
    </div>
    {{-- Utilisé pour afficher certains messages d'erreur --}}
    <div class="hidden mb-8 block text-sm text-left text-red-600 bg-red-200 border border-red-400 h-12 flex items-center p-4 rounded-sm"
        id="error-text" role="alert">
        Erreur...
    </div>
    <a href="{{ route('registre-incidence.create') }}"
        class="my-4 px-4 py-3 bg-green-600 rounded-md text-white font-medium tracking-wide hover:bg-green-500 ml-3 inline-block font-bold">
        Ajouter un élément</a>

    <table class="min-w-full table-auto" id="main-table">
        <thead class="justify-between">
            <tr class="bg-gray-800">
                <th class="px-16 py-2">
                    <span class="text-gray-300">Id</span>
                </th>
                <th class="px-16 py-2">
                    <span class="text-gray-300">Date</span>
                </th>
                <th class="px-16 py-2">
                    <span class="text-gray-300">Région</span>
                </th>
                <th class="px-16 py-2">
                    <span class="text-gray-300">Nombre d'admis en réanimation</span>
                </th>
                <th class="px-16 py-2">
                    <span class="text-gray-300">Action</span>
                </th>
            </tr>
        </thead>
        <tbody class="bg-gray-200">
            @foreach ($data as $item)
                <tr>
                    <td class="px-16 py-2 text-center">{{ $item['id'] }}</td>
                    <td class="px-16 py-2 text-center">{{ $item['jour'] }}</td>
                    <td class="px-16 py-2 text-center">{{ $item['nomReg'] }} ({{ $item['numReg'] }})</td>
                    <td class="px-16 py-2 text-center">{{ $item['incid_rea'] }}</td>
                    <td class="px-16 py-2 text-center">
                        @if(session()->has('auth-token'))
                        <button onclick="window.location.href = `${window.location.origin}/registre-incidence/{{ $item['id'] }}/edit`"
                            class="text-white hover:text-indigo-900 bg-blue-600 hover:bg-blue-500 p-2 mr-2 rounded-md">Edit</button>
                        <button class="text-white hover:text-red-900 bg-red-600 hover:bg-red-500 p-2 mr-2 rounded-md"
                            onclick="deleteComment({{ $item['id'] }})">Delete</button>
                        @else
                        Veuillez vous connecter
                        @endif
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection

@section('body-javascript')
    <script>
        function deleteComment(number) {
            if (confirm('Souhaitez-vous réellement supprimer cette donnée') == false) {
                return;
            }

            const authTokenTag = document.querySelector('meta[name="auth-token"]');
            const textError = document.querySelector('#error-text');
            const textSuccess = document.querySelector("#success-text");

            if (authTokenTag.getAttribute('type') === 'bearer' || authTokenTag.content.length >
                0) {
                axios.delete(`http://localhost:8080/api/registre-incidence/${number}`, {
                        headers: {
                            authorization: `Bearer ${authTokenTag.content}`
                        }
                    })
                    .then(response => {
                        // On cache une possible erreur affichée
                        textError.textContent = "";
                        textError.classList.add("hidden");

                        // On affiche un message de succès
                        textSuccess.classList.remove("hidden");
                        textSuccess.textContent =
                            "L'élément a été supprimé avec succès. Veuillez recharger la page.";
                    })
                    .catch(err => {
                        // On va afficher une erreur (on cache le message de succès au cas où il serait affiché)
                        textError.classList.remove("hidden");
                        textSuccess.classList.add("hidden");

                        if (err.response) {
                            switch (err.response.status) {
                                case 401:
                                    textError.textContent = "Utilisateur non connecté";
                                    break;
                                case 403:
                                    textError.textContent =
                                        "Vous n'avez pas les droits nécessaires";
                                    break;
                                case 404:
                                    textError.textContent =
                                        "L'élément n'existe pas ou plus";
                                    break;
                                case 500:
                                default:
                                    textError.textContent = "Erreur inconnue";
                                    break;
                            }
                        } else {
                            // Erreur inconnue
                            textError.textContent = "Erreur inconnue";
                        }
                    });
            }
        };

    </script>
@endsection

front/resources/views/reg-incid/index.blade.php
@extends('layout')

@section('body')
    {{-- Utilisé pour afficher certains messages de succès --}}
    <div class="hidden mb-8 block text-sm text-left text-green-600 bg-green-200 border border-green-400 h-12 flex items-center p-4 rounded-sm"
        id="success-text" role="alert">
        Succès...
    </div>
    {{-- Utilisé pour afficher certains messages d'erreur --}}
    <div class="hidden mb-8 block text-sm text-left text-red-600 bg-red-200 border border-red-400 h-12 flex items-center p-4 rounded-sm"
        id="error-text" role="alert">
        Erreur...
    </div>
    <a href="{{ route('registre-incidence.create') }}"
        class="my-4 px-4 py-3 bg-green-600 rounded-md text-white font-medium tracking-wide hover:bg-green-500 ml-3 inline-block font-bold">
        Ajouter un élément</a>

    <table class="min-w-full table-auto" id="main-table">
        <thead class="justify-between">
            <tr class="bg-gray-800">
                <th class="px-16 py-2">
                    <span class="text-gray-300">Id</span>
                </th>
                <th class="px-16 py-2">
                    <span class="text-gray-300">Date</span>
                </th>
                <th class="px-16 py-2">
                    <span class="text-gray-300">Région</span>
                </th>
                <th class="px-16 py-2">
                    <span class="text-gray-300">Nombre d'admis en réanimation</span>
                </th>
                <th class="px-16 py-2">
                    <span class="text-gray-300">Action</span>
                </th>
            </tr>
        </thead>
        <tbody class="bg-gray-200">

        </tbody>
    </table>

    <div class="mt-4 flex justify-center">
        <button id="previous_button"
            class="border border-blue-500 text-blue-500 block rounded-sm font-bold py-4 px-6 mr-2 flex items-center hover:bg-blue-500 hover:text-white rounded disabled:opacity-50">
            <svg class="h-5 w-5 mr-2 fill-current" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg"
                xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="-49 141 512 512"
                style="enable-background:new -49 141 512 512;" xml:space="preserve">
                <path id="XMLID_10_"
                    d="M438,372H36.355l72.822-72.822c9.763-9.763,9.763-25.592,0-35.355c-9.763-9.764-25.593-9.762-35.355,0 l-115.5,115.5C-46.366,384.01-49,390.369-49,397s2.634,12.989,7.322,17.678l115.5,115.5c9.763,9.762,25.593,9.763,35.355,0 c9.763-9.763,9.763-25.592,0-35.355L36.355,422H438c13.808,0,25-11.193,25-25S451.808,372,438,372z">
                </path>
            </svg>
            Page précédente
        </button>
        <button id="next_button"
            class="border border-blue-500 bg-blue-500 text-white block rounded-sm font-bold py-4 px-6 ml-2 flex items-center rounded disabled:opacity-50">
            Page suivante
            <svg class="h-5 w-5 ml-2 fill-current" clasversion="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg"
                xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="-49 141 512 512"
                style="enable-background:new -49 141 512 512;" xml:space="preserve">
                <path id="XMLID_11_"
                    d="M-24,422h401.645l-72.822,72.822c-9.763,9.763-9.763,25.592,0,35.355c9.763,9.764,25.593,9.762,35.355,0
                                l115.5-115.5C460.366,409.989,463,403.63,463,397s-2.634-12.989-7.322-17.678l-115.5-115.5c-9.763-9.762-25.593-9.763-35.355,0
                                c-9.763,9.763-9.763,25.592,0,35.355l72.822,72.822H-24c-13.808,0-25,11.193-25,25S-37.808,422-24,422z" />
            </svg>
        </button>
    </div>
@endsection

@section('body-javascript')
    <script>
        (async () => {
            /**
             * Gestion du tableau de données
             */
            // Déclaration de variables
            const table = document.querySelector('#main-table');
            // On va déterminer l'index de la page actuelle
            const urlParams = new URLSearchParams(window.location.search);
            const currentPageIndex = urlParams.get('page') || 1;

            // Call ajax pour récupérer les informations
            const response = await axios.get(
                `http://localhost:8080/api/registre-incidence?page=${currentPageIndex}`);

            // Initialisation de variable en rapport avec les données reçues
            const collection = response.data.collection;
            const onFirstPage = response.data.onFirstPage;
            const hasMorePages = response.data.hasMorePages;

            // Affichage de la collection dans le tableau
            if (!collection.length) {
                // Message si la collection est vide
                let tr = document.createElement('tr');
                tr.classList.add("bg-white", "border-4", "border-gray-200");
                let td = document.createElement("td");
                td.classList.add("text-center");
                td.colSpan = 5;
                td.appendChild(document.createTextNode("Aucun élément"));
                tr.appendChild(td);
                table.tBodies[0].appendChild(tr);
            } else {
                // Message si la collection a au moins un élément. La boucle va ajouter ligne par ligne les éléments
                for (const dataRow of collection) {
                    // Création d'une ligne
                    let tr = document.createElement('tr');
                    tr.classList.add("bg-white", "border-4", "border-gray-200");
                    let td = document.createElement("td");
                    td.appendChild(document.createTextNode(dataRow.id));
                    td.classList.add("px-16", "py-2", "text-center");
                    tr.appendChild(td);

                    td = document.createElement("td");
                    td.appendChild(document.createTextNode(dataRow.jour));
                    td.classList.add("px-16", "py-2", "text-center");
                    tr.appendChild(td);

                    td = document.createElement("td");
                    td.appendChild(document.createTextNode(dataRow.nomReg + " (" + dataRow.numReg +
                        ")"));
                    td.classList.add("px-16", "py-2", "text-center");
                    tr.appendChild(td);

                    td = document.createElement("td");
                    td.appendChild(document.createTextNode(dataRow.incid_rea));
                    td.classList.add("px-16", "py-2", "text-center");
                    tr.appendChild(td);

                    td = document.createElement("td");

                    // Si l'utilisateur est connecté
                    const authTokenTag = document.querySelector('meta[name="auth-token"]');
                    if (authTokenTag.getAttribute('type')=== 'bearer' && authTokenTag.content.length > 0) {
                        // Edit button
                        let button = document.createElement("button");
                        button.classList.add("text-white", "hover:text-indigo-900", "bg-blue-600",
                            "hover:bg-blue-500", "p-2", "mr-2", "rounded-md");
                        button.appendChild(document.createTextNode("Edition"));
                        button.onclick = () => {
                            window.location.href = `${window.location.pathname}/${dataRow.id}/edit`
                        };
                        td.appendChild(button);

                        // Delete button
                        button = document.createElement("button");
                        button.classList.add("text-white", "hover:text-red-900", "bg-red-600", "hover:bg-red-500",
                            "p-2", "mr-2", "rounded-md");
                        button.appendChild(document.createTextNode("Supprimer"));
                        button.onclick = () => {
                            if (confirm('Souhaitez-vous réellement supprimer cette donnée') == true) {
                                entityDelete(dataRow.id)
                            }
                        };
                        td.appendChild(button);
                    } else {
                        td.innerText = "Veuillez vous connecter";
                    }
                    tr.appendChild(td);

                    // Remplissage d'une ligne dans le tableau
                    table.tBodies[0].appendChild(tr);
                }
            }

            /**
             * Gestion des bouttons de pagination
             */
            // Déclaration de variables
            const previousButton = document.querySelector("#previous_button");
            const nextButton = document.querySelector("#next_button");

            // Blocage des boutons si l'on se trouve à la première ou la dernière page
            if (onFirstPage) {
                previousButton.disabled = true;
            }
            if (!hasMorePages) {
                nextButton.disabled = true;
            }

            // Changement de la page au click
            previousButton.addEventListener("click", (event) => {
                document.location.href = `?page=${parseInt(currentPageIndex) - 1}`;
            });
            nextButton.addEventListener("click", (event) => {
                document.location.href = `?page=${parseInt(currentPageIndex) + 1}`;
            });
        })();

        /**
         * Action de suppression d'un item
         */
        function entityDelete(number) {
            // On va récupérer la balise html contenant le token de connexion
            const authTokenTag = document.querySelector('meta[name="auth-token"]');
            const textError = document.querySelector('#error-text');
            const textSuccess = document.querySelector("#success-text");


            if (authTokenTag.getAttribute('type') === 'bearer' || authTokenTag.content.length > 0) {
                axios.delete(`http://localhost:8080/api/registre-incidence/${number}`, {
                        headers: {
                            authorization: `Bearer ${authTokenTag.content}`
                        }
                    })
                    .then(response => {
                        // On cache une possible erreur affichée
                        textError.textContent = "";
                        textError.classList.add("hidden");

                        // On affiche un message de succès
                        textSuccess.classList.remove("hidden");
                        textSuccess.textContent = "L'élément a été supprimé avec succès. Veuillez recharger la page.";
                    })
                    .catch(err => {
                        // On va afficher une erreur (on cache le message de succès au cas où il serait affiché)
                        textError.classList.remove("hidden");
                        textSuccess.classList.add("hidden");

                        if (err.response) {
                            switch (err.response.status) {
                                case 401:
                                    textError.textContent = "Utilisateur non connecté";
                                    break;
                                case 403:
                                    textError.textContent = "Vous n'avez pas les droits nécessaires";
                                    break;
                                case 404:
                                    textError.textContent = "L'élément n'existe pas ou plus";
                                    break;
                                case 500:
                                default:
                                    textError.textContent = "Erreur inconnue";
                                    break;
                            }
                        } else {
                            // Erreur inconnue
                            textError.textContent = "Erreur inconnue";
                        }
                    });
            }

        }

    </script>
@endsection